#!/usr/bin/env python3
"""
Generate fe16_mul.S: 68000 assembly for multiplying and squaring numbers
mod 2^255-19, stored as 16 limbs of 16 bits (see src/x25519/fe16.h).

Fully unrolled product scanning: for each output column k, add up every
a[i]*b[k-i] (one MULU.W each) into a 48-bit accumulator, emit the low 16
bits, shift the accumulator down. Then fold the top 256 bits back into the
bottom (2^256 = 38 mod p).

Registers:
  a0 = r, a1 = a, a2 = b
  d3 = accumulator low 32 bits, d4 = accumulator high bits (carries)
  d5/d6 = cross-product accumulator when squaring
  d7 = 0 (for ADDX)
  64 bytes of stack hold the 512-bit product.

C prototypes:
  void fe16_mul(fe16 r, const fe16 a, const fe16 b);
  void fe16_sq(fe16 r, const fe16 a);
"""
import sys

SAVED = "%d2-%d7/%a2"
SAVED_BYTES = 7 * 4
TMP = 64


def limb(reg, i):
    return f"({reg})" if i == 0 else f"{2 * i}({reg})"


def prologue(out, name, nargs):
    out += [
        "",
        f"\t.globl\t{name}",
        f"\t.type\t{name}, @function",
        f"{name}:",
        f"\tmovem.l\t{SAVED},-(%sp)",
        f"\tlea\t-{TMP}(%sp),%sp",
    ]
    base = TMP + SAVED_BYTES
    out.append(f"\tmove.l\t{base + 4}(%sp),%a0")
    out.append(f"\tmove.l\t{base + 8}(%sp),%a1")
    if nargs == 3:
        out.append(f"\tmove.l\t{base + 12}(%sp),%a2")
    out += ["\tmoveq\t#0,%d3", "\tmoveq\t#0,%d4", "\tmoveq\t#0,%d7"]


def end_column(out, k):
    out += [
        f"\tmove.w\t%d3,{limb('%sp', k)}",   # emit low 16 bits
        "\tmove.w\t%d4,%d3",                  # acc >>= 16
        "\tswap\t%d3",
        "\tmoveq\t#0,%d4",
    ]


def reduce_and_return(out, name):
    out.append("\tmove.w\t%d3,62(%sp)")       # top limb of the product
    out.append("\t| fold: r = lo + 38 * hi")
    out.append("\tmoveq\t#0,%d3")
    for i in range(16):
        out += [
            f"\tmove.w\t{2 * (i + 16)}(%sp),%d1",
            "\tmulu.w\t#38,%d1",
            "\tadd.l\t%d1,%d3",
            "\tmoveq\t#0,%d2",
            f"\tmove.w\t{limb('%sp', i)},%d2",
            "\tadd.l\t%d2,%d3",
            f"\tmove.w\t%d3,{limb('%a0', i)}",
            "\tclr.w\t%d3",
            "\tswap\t%d3",
        ]
    out.append("\t| fold the last carry (< 40) the same way")
    out += ["\tmulu.w\t#38,%d3", "\tadd.w\t%d3,(%a0)"]
    for i in range(1, 16):
        out += [
            f"\tmove.w\t{limb('%a0', i)},%d1",   # MOVE leaves X alone
            "\taddx.w\t%d7,%d1",
            f"\tmove.w\t%d1,{limb('%a0', i)}",
        ]
    out += [
        "\t| a final carry means we wrapped past 2^256: add 38 more",
        "\tsubx.w\t%d1,%d1",
        "\tand.w\t#38,%d1",
        "\tadd.w\t%d1,(%a0)",
        f"\tlea\t{TMP}(%sp),%sp",
        f"\tmovem.l\t(%sp)+,{SAVED}",
        "\trts",
        f"\t.size\t{name}, .-{name}",
    ]


def gen_mul(out):
    prologue(out, "fe16_mul", 3)
    for k in range(31):
        out.append(f"\t| column {k}")
        for i in range(max(0, k - 15), min(15, k) + 1):
            out += [
                f"\tmove.w\t{limb('%a1', i)},%d1",
                f"\tmulu.w\t{limb('%a2', k - i)},%d1",
                "\tadd.l\t%d1,%d3",
                "\taddx.w\t%d7,%d4",
            ]
        end_column(out, k)
    reduce_and_return(out, "fe16_mul")


def gen_sq(out):
    prologue(out, "fe16_sq", 2)
    for k in range(31):
        out.append(f"\t| column {k}")
        pairs = [(i, k - i) for i in range(max(0, k - 15), 16) if i < k - i <= 15]
        if pairs:
            # Cross products a[i]*a[j] (i < j) appear twice: sum once, double.
            out += ["\tmoveq\t#0,%d5", "\tmoveq\t#0,%d6"]
            for i, j in pairs:
                out += [
                    f"\tmove.w\t{limb('%a1', i)},%d1",
                    f"\tmulu.w\t{limb('%a1', j)},%d1",
                    "\tadd.l\t%d1,%d5",
                    "\taddx.w\t%d7,%d6",
                ]
            out += [
                "\tadd.l\t%d5,%d5",
                "\taddx.w\t%d6,%d6",
                "\tadd.l\t%d5,%d3",
                "\taddx.w\t%d6,%d4",
            ]
        if k % 2 == 0:
            out += [
                f"\tmove.w\t{limb('%a1', k // 2)},%d1",
                "\tmulu.w\t%d1,%d1",
                "\tadd.l\t%d1,%d3",
                "\taddx.w\t%d7,%d4",
            ]
        end_column(out, k)
    reduce_and_return(out, "fe16_sq")


def main():
    out = ["| Generated by tools/gen_fe16.py -- do not edit.", "\t.text", "\t.even"]
    gen_mul(out)
    gen_sq(out)
    text = "\n".join(out) + "\n"
    if len(sys.argv) > 1:
        open(sys.argv[1], "w").write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
